# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guillaume St-Onge
subtitle: Ph.D. candidate in Physics
author: Guillaume St-Onge
email: guillaume.st-onge.4@ulaval.ca
description: > # this means to ignore newlines until "baseurl:"
    Personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gstonge.ca" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: stonge_g
github_username: gstonge

# Build settings
markdown: kramdown


social:
  - name: Twitter
    icon: fab fa-twitter
    username: stonge_g
    url: https://twitter.com/stonge_g
    desc: Follow me on Twitter

  - name: Linkedin
    icon: fab fa-linkedin-in
    url: https://www.linkedin.com/in/guillaume-st-onge-461b62128

  - name: GitHub
    icon: fab fa-github
    username: gstonge
    url: https://github.com/gstonge
    desc: See my projects on Github

  - name: Google Scholar
    icon: fas fa-graduation-cap
    username: Guillaume St-Onge
    url: https://scholar.google.com/citations?user=UwKTgecAAAAJ
    desc: My publications

  - name: ORCID
    icon: fab fa-orcid
    url: https://orcid.org/0000-0001-5415-3748
    username: Guillaume St-Onge

#Define excerpt_separator
excerpt_separator: <!--more-->
